# curl --location --request PUT 'localhost:8080/user/08dd0b34-1c7f-4849-b252-122d0c3c53b9' <- user_id
#--header 'Content-Type: application/json'
#--data '{
#  "password": "mukul123456",
#  "first_name": "Mukul",
#  "last_name": "Mantosh"
#}
#'
PUT localhost:8080/user/08dd0b34-1c7f-4849-b252-122d0c3c53b9
Content-Type: application/json

{
  "password": "mukul123456",
  "first_name": "Mukul",
  "last_name": "Mantosh"
}


###

