# curl --location 'localhost:8080/cart/add-user'
#--header 'Content-Type: application/json'
#--data '{
#    "user_id": "13315282-428f-400e-b987-f3218b263af5", <-- user_id
#    "total": 0
#}'
POST localhost:8080/cart/add-user
Content-Type: application/json

{
  "user_id": "13315282-428f-400e-b987-f3218b263af5",
  "total": 0
}

###

