# curl --location --request PUT 'localhost:8080/user/address/430106b3-1c47-421f-92aa-ee612d0f8542'
#--header 'Content-Type: application/json'
#--data '{
#  "address": "King Street, Kingston, New York",
#  "city": "NEW YORK",
#  "postal_code": "12401",
#  "country": "United States of America",
#  "mobile": "122345666"
#}'
PUT localhost:8080/user/address/430106b3-1c47-421f-92aa-ee612d0f8542
Content-Type: application/json

{
  "address": "King Street, Kingston, New York",
  "city": "NEW YORK",
  "postal_code": "12401",
  "country": "United States of America",
  "mobile": "122345666"
}

###

