# curl --location 'localhost:8080/category'
#--header 'Content-Type: application/json'
#--data '{
#    "name": "Electronics",
#    "description": "Electronics - Mobile Devices"
#}'
POST localhost:8080/category
Content-Type: application/json

{
  "name": "Electronics",
  "description": "Electronics - Mobile Devices"
}

###

