apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: go-ecommerce
data:
  JWT_SECRET: "*********"               # Provide Random Secret Text
  DB_HOST: "database-service"           # Name of service db-service (refer db-service.yml)
  DB_USERNAME: "**********"             # Database Username
  DB_PASSWORD: "*********"              # Database Password
  DB_NAME: "**********"                 # Database Name
  DB_PORT: "*********"                  # Database Port

# Production Recommend: Kubernetes Secrets, External Secret Management Tool.