apiVersion: v1
kind: Service
metadata:
  name: go-ecommerce-lb
  namespace: go-ecommerce
spec:
  type: LoadBalancer
  selector:
    app: go-ecommerce-app
  ports:
    - name: http
      port: 80
      targetPort: 8080