apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ecommerce-deploy
  namespace: go-ecommerce
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go-ecommerce-app
  template:
    metadata:
      labels:
        app: go-ecommerce-app
    spec:
      containers:
        - image: <DOCKER_IMAGE_URL>
          imagePullPolicy: Always
          name: go-ecomm-container
          envFrom:
            - configMapRef:
                name: app-cm
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
                - NET_RAW
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3


