# curl --location 'localhost:8080/products'
#--header 'Content-Type: application/json'
#--data '{
#    "name": "IPhone 14",
#    "description": "The iPhone 14 and iPhone 14 Plus are smartphones designed, developed, and marketed by Apple Inc. They are the sixteenth and latest generation of iPhones",
#    "quantity": 20,
#    "category_id": "4d3e7c6e-5f43-43fe-ad7a-1553ad1e3f73" # <<-- you will receive when you create a new category
#}'
POST localhost:8080/products
Content-Type: application/json

{
  "name": "IPhone 15",
  "description": "Iphone 15",
  "quantity": 20,
  "price": 999,
  "category_id": "f61040f5-c291-4e38-a506-c86fc423eb64"
}

###

