apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: go-ecommerce
data:
  JWT_SECRET: "secret"
  DB_HOST: "postgres-service"
  DB_USERNAME: "sample"
  DB_PASSWORD: "sample123"
  DB_NAME: "ecommerce"
  DB_PORT: "5432"

