name: Generate code coverage badge
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    name: Update coverage badge
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'


      - name: Run Test
        run: |
          make test

      - name: generate Test Coverage
        run: make coverage

      - name: check Test Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml

      - name: make coverage badge
        uses: action-badges/core@0.2.2
        if: contains(github.ref, 'master')
        with:
          label: coverage
          message: ${{ steps.coverage.outputs.badge-text }}
          message-color: ${{ steps.coverage.outputs.badge-color }}
          file-name: coverage.svg
          badge-branch: badges ## orphan branch where badge will be committed
          github-token: "${{ secrets.GITHUB_TOKEN }}"

